In [3]:
import pandas as pd 
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler 
from sklearn.preprocessing import LabelEncoder
import torch

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/virajbhutada/breast-cancer-prediction/refs/heads/main/data/breast_cancer_data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [5]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
# All other columns
X = df.iloc[:, 1:]
# Diagnosis column
y = df.iloc[:,0] 
# print(X,y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train, X_test, y_train, y_test)

     radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
68         9.029         17.33           58.79      250.5          0.10660
181       21.090         26.57          142.70     1311.0          0.11410
63         9.173         13.86           59.20      260.9          0.07721
248       10.650         25.22           68.01      347.0          0.09657
60        10.170         14.88           64.55      311.9          0.11340
..           ...           ...             ...        ...              ...
71         8.888         14.64           58.79      244.0          0.09783
106       11.640         18.33           75.17      412.5          0.11420
270       14.290         16.82           90.30      632.6          0.06429
435       13.980         19.62           91.12      599.5          0.10600
102       12.180         20.52           77.22      458.7          0.08013

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
68            0.14130         0.31300              0.04375         0.2111
181           0.28320         0.24870              0.14960         0.2395
63            0.08751         0.05988              0.02180         0.2341
248           0.07234         0.02379              0.01615         0.1897
60            0.08061         0.01084              0.01290         0.2743
..                ...             ...                  ...            ...
71            0.15310         0.08606              0.02872         0.1902
106           0.10170         0.07070              0.03485         0.1801
270           0.02675         0.00725              0.00625         0.1508
435           0.11330         0.11260              0.06463         0.1669
102           0.04038         0.02383              0.01770         0.1739

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
68                  0.08046  ...        10.310          22.65
181                 0.07398  ...        26.680          33.48
63                  0.06963  ...        10.010          19.23
248                 0.06329  ...        12.250          35.19
60                  0.06960  ...        11.020          17.45
..                      ...  ...           ...            ...
71                  0.08980  ...         9.733          15.67
106                 0.06520  ...        13.140          29.26
270                 0.05376  ...        14.910          20.65
435                 0.06544  ...        17.040          30.80
102                 0.05677  ...        13.340          32.84

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
68             65.50       324.7           0.14820            0.43650
181           176.50      2089.0           0.14910            0.75840
63             65.59       310.1           0.09836            0.16780
248            77.98       455.7           0.14990            0.13980
60             69.86       368.6           0.12750            0.09866
..               ...         ...               ...                ...
71             62.56       284.4           0.12070            0.24360
106            85.51       521.7           0.16880            0.26600
270            94.44       684.6           0.08567            0.05036
435           113.90       869.3           0.16130            0.35680
102            84.58       547.8           0.11230            0.08862

     concavity_worst  concave points_worst  symmetry_worst  \
68           1.25200               0.17500          0.4228
181          0.67800               0.29030          0.4098
63           0.13970               0.05087          0.3282
248          0.11250               0.06136          0.3409
60           0.02168               0.02579          0.3557
..               ...                   ...             ...
71           0.14340               0.04786          0.2254
106          0.28730               0.12180          0.2806
270          0.03866               0.03333          0.2458
435          0.40690               0.18270          0.3179
102          0.11450               0.07431          0.2694

     fractal_dimension_worst
68                   0.11750
181                  0.12840
63                   0.08490
248                  0.08147
60                   0.08020
..                       ...
71                   0.10840
106                  0.09097
270                  0.06120
435                  0.10550
102                  0.06878

[455 rows x 30 columns]      radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
204        12.47         18.60           81.09      481.9          0.09965
70         18.94         21.31          123.60     1130.0          0.09009
131        15.46         19.48          101.70      748.9          0.10920
431        12.40         17.68           81.47      467.8          0.10540
540        11.54         14.44           74.65      402.9          0.09984
..           ...           ...             ...        ...              ...
486        14.64         16.85           94.21      666.0          0.08641
75         16.07         19.65          104.10      817.7          0.09168
249        11.52         14.93           73.87      406.3          0.10130
238        14.22         27.85           92.55      623.9          0.08223
265        20.73         31.12          135.70     1419.0          0.09469

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
204           0.10580         0.08005              0.03821         0.1925
70            0.10290         0.10800              0.07951         0.1582
131           0.12230         0.14660              0.08087         0.1931
431           0.13160         0.07741              0.02799         0.1811
540           0.11200         0.06737              0.02594         0.1818
..                ...             ...                  ...            ...
486           0.06698         0.05192              0.02791         0.1409
75            0.08424         0.09769              0.06638         0.1798
249           0.07808         0.04328              0.02929         0.1883
238           0.10390         0.11030              0.04408         0.1342
265           0.11430         0.13670              0.08646         0.1769

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
204                 0.06373  ...         14.97          24.64
70                  0.05461  ...         24.86          26.58
131                 0.05796  ...         19.26          26.00
431                 0.07102  ...         12.88          22.91
540                 0.06782  ...         12.26          19.68
..                      ...  ...           ...            ...
486                 0.05355  ...         16.46          25.44
75                  0.05391  ...         19.77          24.56
249                 0.06168  ...         12.65          21.19
238                 0.06129  ...         15.75          40.54
265                 0.05674  ...         32.49          47.16

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
204            96.05       677.9            0.1426             0.2378
70            165.90      1866.0            0.1193             0.2336
131           124.90      1156.0            0.1546             0.2394
431            89.61       515.8            0.1450             0.2629
540            78.78       457.8            0.1345             0.2118
..               ...         ...               ...                ...
486           106.00       831.0            0.1142             0.2070
75            128.80      1223.0            0.1500             0.2045
249            80.88       491.8            0.1389             0.1582
238           102.50       764.0            0.1081             0.2426
265           214.00      3432.0            0.1401             0.2644

     concavity_worst  concave points_worst  symmetry_worst  \
204           0.2671               0.10150          0.3014
70            0.2687               0.17890          0.2551
131           0.3791               0.15140          0.2837
431           0.2403               0.07370          0.2556
540           0.1797               0.06918          0.2329
..               ...                   ...             ...
486           0.2437               0.07828          0.2455
75            0.2829               0.15200          0.2650
249           0.1804               0.09608          0.2664
238           0.3064               0.08219          0.1890
265           0.3442               0.16590          0.2868

     fractal_dimension_worst
204                  0.08750
70                   0.06589
131                  0.08019
431                  0.09359
540                  0.08134
..                       ...
486                  0.06596
75                   0.06387
249                  0.07809
238                  0.07796
265                  0.08218

[114 rows x 30 columns] 68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object 204    B
70     M
131    M
431    B
540    B
      ..
486    B
75     M
249    B
238    B
265    M
Name: diagnosis, Length: 114, dtype: object

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)
print(X_train, X_test)

[[-1.44075296 -0.43531947 -1.36208497 ...  0.9320124   2.09724217
   1.88645014]
 [ 1.97409619  1.73302577  2.09167167 ...  2.6989469   1.89116053
   2.49783848]
 [-1.39998202 -1.24962228 -1.34520926 ... -0.97023893  0.59760192
   0.0578942 ]
 ...
 [ 0.04880192 -0.55500086 -0.06512547 ... -1.23903365 -0.70863864
  -1.27145475]
 [-0.03896885  0.10207345 -0.03137406 ...  1.05001236  0.43432185
   1.21336207]
 [-0.54860557  0.31327591 -0.60350155 ... -0.61102866 -0.3345212
  -0.84628745]] [[-0.4877952  -0.25088379 -0.46378664 ... -0.21989091  0.23083947
   0.17173277]
 [ 1.37325734  0.36318719  1.29254295 ...  0.93019499 -0.58958803
  -0.972629  ]
 [ 0.37225845 -0.05148067  0.38772954 ...  0.52157274 -0.08280128
  -0.21536971]
 ...
 [-0.76105639 -1.08248546 -0.76208585 ... -0.30042664 -0.3893541
  -0.32657562]
 [ 0.01558068  1.84511495  0.00969106 ... -0.50681802 -1.76086788
  -0.33345979]
 [ 1.88813896  2.58607883  1.79246268 ...  0.73702811 -0.02786985
  -0.10998887]]

In [8]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train).astype(float)
y_test = encoder.fit_transform(y_test).astype(float)
print(y_train, y_test)

[0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 0.
 0. 1. 0. 1. 0. 0. 1. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0.
 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1.
 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1.
 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1.
 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1.
 0. 1. 1. 0. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1.
 0. 1. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0.
 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 1.
 1. 1. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 0.
 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 1.
 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 0. 0. 0.
 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0.] [0. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0. 1. 0.
 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0. 1. 1.
 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 0. 1. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1.]

In [9]:
# Convert numpy arrays to PyTorch tensors 
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)
print(X_train_tensor, X_test_tensor, y_train_tensor, y_test_tensor)

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64) tensor([[-0.4878, -0.2509, -0.4638,  ..., -0.2199,  0.2308,  0.1717],
        [ 1.3733,  0.3632,  1.2925,  ...,  0.9302, -0.5896, -0.9726],
        [ 0.3723, -0.0515,  0.3877,  ...,  0.5216, -0.0828, -0.2154],
        ...,
        [-0.7611, -1.0825, -0.7621,  ..., -0.3004, -0.3894, -0.3266],
        [ 0.0156,  1.8451,  0.0097,  ..., -0.5068, -1.7609, -0.3335],
        [ 1.8881,  2.5861,  1.7925,  ...,  0.7370, -0.0279, -0.1100]],
       dtype=torch.float64) tensor([0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1.,
        0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0.,
        1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
        0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
        1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
        1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1.,
        0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
        1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
        0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1.,
        0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1.,
        0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1.,
        1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
        0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1.,
        0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1.,
        1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1.,
        1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0.,
        1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0.,
        0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0.,
        0., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0.,
        0., 0., 0., 1., 0.], dtype=torch.float64) tensor([0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
        0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
        0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1.,
        0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1.,
        0., 0., 1., 0., 0., 1.], dtype=torch.float64)

In [10]:
from torch.utils.data import Dataset, DataLoader

class CustomDataSet(Dataset):
    def __init__(self, features, labels):
        self.features = features 
        self.labels = labels

    def __len__(self):
        return len(self.features)
    
    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

In [11]:
class MySimpleNNCustom:
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        # Z = Wx + b
        z = torch.matmul(X, self.weights) + self.bias 
        y_pred = torch.sigmoid(z)
        return y_pred 

    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

In [12]:
import torch.nn as nn

class MySimpleNN(nn.Module):
    def __init__(self, X):
        super().__init__()
        self.linear = nn.Linear(X, 1, dtype=torch.float64) 
        self.sigmoid = nn.Sigmoid()

    def forward(self, X):
        out = self.linear(X)
        out = self.sigmoid(out)
        return out

In [13]:
learning_rate = 0.1 
epochs = 20
loss_function = nn.BCELoss()

In [14]:
train_dataset = CustomDataSet(X_train_tensor, y_train_tensor)
test_dataset = CustomDataSet(X_test_tensor, y_test_tensor)

test_dataset

In [17]:
train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=2, shuffle=True)
test_loader

In [ ]:
# Create model
model = MySimpleNN(X_train_tensor.shape[1])

# Create optimizer 
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# Loop through epochs
for epochs in range(epochs):

    for batch_features, batch_labels in train_loader:

        # Forward pass
        y_pred = model(batch_features) 
        # y_pred = model.forward(X_train_tensor) 
        
        # Loss calculate 
        # loss = model.loss_function(y_pred, y_train_tensor)
        loss = loss_function(y_pred, batch_labels.view(-1,1))    

        # Clear gradients
        optimizer.zero_grad()

        # Backward pass  
        loss.backward()

        # Parameters update 
        optimizer.step() 

        # Weight update: W(new) - W(old) - n(dl/dw) 
        # with torch.no_grad():
        #     model.linear.weight -= learning_rate * model.linear.weight.grad 
        #     model.linear.bias -= learning_rate * model.linear.bias.grad

        # Reset gradients before next epoch 
        # model.linear.weights.grad.zero_()
        # model.linear.bias.grad.zero_()

        print(f"Epoch: {epochs+1} Loss: {loss.item()}")

Epoch: 1 Loss: 0.9004230519291962
Epoch: 1 Loss: 0.5630210740281404
Epoch: 1 Loss: 0.13338872422328235
Epoch: 1 Loss: 0.6209973312804484
Epoch: 1 Loss: 0.41187100653605274
Epoch: 1 Loss: 0.2282003252332314
Epoch: 1 Loss: 0.1090172124623798
Epoch: 1 Loss: 0.12566433993841658
Epoch: 1 Loss: 0.25594816992043085
Epoch: 1 Loss: 0.3678517946999187
Epoch: 1 Loss: 0.5554420393748402
Epoch: 1 Loss: 0.0543599812726882
Epoch: 1 Loss: 0.12558025956094107
Epoch: 1 Loss: 0.03203320717964442
Epoch: 1 Loss: 0.11888568129161498
Epoch: 1 Loss: 0.16455838377863327
Epoch: 1 Loss: 0.3494497705997548
Epoch: 1 Loss: 0.08119031611978555
Epoch: 1 Loss: 0.016337431805265708
Epoch: 1 Loss: 0.0728715090164142
Epoch: 1 Loss: 0.0638612607535822
Epoch: 1 Loss: 0.09010465438224985
Epoch: 1 Loss: 0.20658519588693758
Epoch: 1 Loss: 1.0163397168368014
Epoch: 1 Loss: 0.19141442331263125
Epoch: 1 Loss: 0.29868736182463534
Epoch: 1 Loss: 0.09237080603602554
Epoch: 1 Loss: 0.4889564084003096
Epoch: 1 Loss: 0.06683060722189163
Epoch: 1 Loss: 0.3329745780881923
Epoch: 1 Loss: 0.6820712382762417
Epoch: 1 Loss: 0.16630423243536444
Epoch: 1 Loss: 0.0800110705004903
Epoch: 1 Loss: 0.08957574245738763
Epoch: 1 Loss: 0.11161438868681531
Epoch: 1 Loss: 0.06130703225860745
Epoch: 1 Loss: 0.01819836727174782
Epoch: 1 Loss: 0.022297457872947835
Epoch: 1 Loss: 0.18038597078415758
Epoch: 1 Loss: 0.11563504720688075
Epoch: 1 Loss: 0.10483936173611419
Epoch: 1 Loss: 0.13241257255713224
Epoch: 1 Loss: 0.06302935792471341
Epoch: 1 Loss: 0.6027941374292236
Epoch: 1 Loss: 0.3555270095701419
Epoch: 1 Loss: 0.06710373477251307
Epoch: 1 Loss: 0.07770701758816226
Epoch: 1 Loss: 0.37218952071737055
Epoch: 1 Loss: 0.3082530693876126
Epoch: 1 Loss: 0.03184974074258887
Epoch: 1 Loss: 0.01703718297278521
Epoch: 1 Loss: 0.20826498852068678
Epoch: 1 Loss: 0.02848105348239142
Epoch: 1 Loss: 0.05700005908215673
Epoch: 1 Loss: 0.020942392089699904
Epoch: 1 Loss: 0.08383265771957651
Epoch: 1 Loss: 0.007931205125488328
Epoch: 1 Loss: 0.004764272446335906
Epoch: 1 Loss: 0.14321982981508896
Epoch: 1 Loss: 0.12006207654818024
Epoch: 1 Loss: 0.12476664478120664
Epoch: 1 Loss: 0.06199592224483293
Epoch: 1 Loss: 0.23582756811085237
Epoch: 1 Loss: 0.03188060017110461
Epoch: 1 Loss: 0.009280703291197385
Epoch: 1 Loss: 0.4613389087778721
Epoch: 1 Loss: 0.004882784071845791
Epoch: 1 Loss: 0.15650904159579143
Epoch: 1 Loss: 0.2841495187897621
Epoch: 1 Loss: 0.01786424521903868
Epoch: 1 Loss: 0.14316587282832807
Epoch: 1 Loss: 0.043774173867339936
Epoch: 1 Loss: 0.07130224322911244
Epoch: 1 Loss: 0.09552564821081028
Epoch: 1 Loss: 0.21651740459565144
Epoch: 1 Loss: 0.1427319020069788
Epoch: 1 Loss: 0.14896885010848354
Epoch: 1 Loss: 0.2948497003057005
Epoch: 1 Loss: 0.012022930100919624
Epoch: 1 Loss: 0.0021042126213918037
Epoch: 1 Loss: 0.019103786784538196
Epoch: 1 Loss: 0.264821145201304
Epoch: 1 Loss: 0.003185486293049875
Epoch: 1 Loss: 0.08581938458631505
Epoch: 1 Loss: 0.00809075001309022
Epoch: 1 Loss: 0.13743140986515875
Epoch: 1 Loss: 0.27546444317690116
Epoch: 1 Loss: 0.012772837868989237
Epoch: 1 Loss: 0.009031644539382233
Epoch: 1 Loss: 0.1630435194613755
Epoch: 1 Loss: 0.046065811814756025
Epoch: 1 Loss: 0.0016042193336836018
Epoch: 1 Loss: 0.1149628386465952
Epoch: 1 Loss: 0.2460445231645627
Epoch: 1 Loss: 0.009129749660550109
Epoch: 1 Loss: 0.22443294872481814
Epoch: 1 Loss: 0.019010886272260635
Epoch: 1 Loss: 0.03274872372310858
Epoch: 1 Loss: 0.00894574512269665
Epoch: 1 Loss: 0.10016710275302693
Epoch: 1 Loss: 0.08062365982649698
Epoch: 1 Loss: 0.007871637301512815
Epoch: 1 Loss: 0.016787372614832877
Epoch: 1 Loss: 0.02616701106216691
Epoch: 1 Loss: 0.23205691876582293
Epoch: 1 Loss: 0.006555495796049686
Epoch: 1 Loss: 0.0222352677626849
Epoch: 1 Loss: 0.005034789666127743
Epoch: 1 Loss: 0.04053637770699109
Epoch: 1 Loss: 0.004444078453741414
Epoch: 1 Loss: 0.07367656100373919
Epoch: 1 Loss: 0.05635090381217607
Epoch: 1 Loss: 0.01413998679247395
Epoch: 1 Loss: 0.008966181408262695
Epoch: 1 Loss: 0.4448991340728636
Epoch: 1 Loss: 0.001459408751032486
Epoch: 1 Loss: 0.0008258741941210046
Epoch: 1 Loss: 0.018599271384896685
Epoch: 1 Loss: 0.023900995502698655
Epoch: 1 Loss: 0.1023499052652873
Epoch: 1 Loss: 0.16511625441508138
Epoch: 1 Loss: 0.05153625644376311
Epoch: 1 Loss: 0.2885120146771648
Epoch: 1 Loss: 0.4097965107029478
Epoch: 1 Loss: 0.16610283720500818
Epoch: 1 Loss: 0.35919361952015344
Epoch: 1 Loss: 0.32963241035055946
Epoch: 1 Loss: 0.01309812490441702
Epoch: 1 Loss: 0.020865628970865864
Epoch: 1 Loss: 0.0003779341118964919
Epoch: 1 Loss: 0.0003192974887246025
Epoch: 1 Loss: 0.06838321765056156
Epoch: 1 Loss: 0.002508506107707662
Epoch: 1 Loss: 0.0575449098071697
Epoch: 1 Loss: 0.41477098052920486
Epoch: 1 Loss: 0.06871981195999405
Epoch: 1 Loss: 0.20818899234205954
Epoch: 1 Loss: 0.003101030331717522
Epoch: 1 Loss: 0.028498795495463723
Epoch: 1 Loss: 0.0094426194819441
Epoch: 1 Loss: 0.0051439523238086355
Epoch: 1 Loss: 0.04081037418622532
Epoch: 1 Loss: 0.0466435746680668
Epoch: 1 Loss: 0.024979419446742288
Epoch: 1 Loss: 0.0016584053923664691
Epoch: 1 Loss: 0.007270177644252881
Epoch: 1 Loss: 0.025036309188950657
Epoch: 1 Loss: 0.0015815407440509007
Epoch: 1 Loss: 0.02670556772198142
Epoch: 1 Loss: 0.0026110184475831894
Epoch: 1 Loss: 0.14580740800921568
Epoch: 1 Loss: 0.677710191546264
Epoch: 1 Loss: 0.003279096446742105
Epoch: 1 Loss: 0.01651510037627967
Epoch: 1 Loss: 0.004739467943711298
Epoch: 1 Loss: 0.00721042968837775
Epoch: 1 Loss: 0.02665265025418875
Epoch: 1 Loss: 0.00532287022158742
Epoch: 1 Loss: 0.0009469030628813081
Epoch: 1 Loss: 0.004842765605016619
Epoch: 1 Loss: 0.27540871904539965
Epoch: 1 Loss: 0.1396522174221847
Epoch: 1 Loss: 0.002692805101676434
Epoch: 1 Loss: 0.37205791859150833
Epoch: 1 Loss: 0.10679226017901151
Epoch: 1 Loss: 0.10895659293241965
Epoch: 1 Loss: 0.07630438139298601
Epoch: 1 Loss: 0.09653731282198492
Epoch: 1 Loss: 0.04729626494337015
Epoch: 1 Loss: 0.00043632146633924645
Epoch: 1 Loss: 0.21274468555382756
Epoch: 1 Loss: 0.19772561889596593
Epoch: 1 Loss: 0.32508356500927454
Epoch: 1 Loss: 0.03622424977532278
Epoch: 1 Loss: 0.05156798825878722
Epoch: 1 Loss: 0.18868217417520328
Epoch: 1 Loss: 0.00833903454706211
Epoch: 1 Loss: 2.455554174499016
Epoch: 1 Loss: 0.01803760749042067
Epoch: 1 Loss: 0.0006694947289868627
Epoch: 1 Loss: 0.1211192760303115
Epoch: 1 Loss: 0.019363231153164077
Epoch: 1 Loss: 0.004941561140258931
Epoch: 1 Loss: 0.1938804159086329
Epoch: 1 Loss: 0.2143604192235612
Epoch: 1 Loss: 0.009863205280303704
Epoch: 1 Loss: 0.036976667573130034
Epoch: 1 Loss: 0.028125161753662437
Epoch: 1 Loss: 0.023005907696546285
Epoch: 1 Loss: 0.007416154069278567
Epoch: 1 Loss: 0.22904686571017638
Epoch: 1 Loss: 0.20509831481007787
Epoch: 1 Loss: 0.008229354444307316
Epoch: 1 Loss: 0.0060829715816639865
Epoch: 1 Loss: 0.14410313945912973
Epoch: 1 Loss: 0.024903442401263246
Epoch: 1 Loss: 0.003435929723233788
Epoch: 1 Loss: 0.020066210856215717
Epoch: 1 Loss: 0.001694844995743852
Epoch: 1 Loss: 0.05139562586495118
Epoch: 1 Loss: 0.004247806166395
Epoch: 1 Loss: 0.00626021371531368
Epoch: 1 Loss: 0.22493818588406905
Epoch: 1 Loss: 0.00028016457720604604
Epoch: 1 Loss: 0.002662826904799383
Epoch: 1 Loss: 0.0029906514763361584
Epoch: 1 Loss: 0.2614899209971253
Epoch: 1 Loss: 0.0010966961214134542
Epoch: 1 Loss: 0.009327375813718817
Epoch: 1 Loss: 0.0001002660680136703
Epoch: 1 Loss: 0.00010383403635909065
Epoch: 1 Loss: 0.005714057555184639
Epoch: 1 Loss: 0.0006537824213461712
Epoch: 1 Loss: 0.010557380647171639
Epoch: 1 Loss: 0.034988754989733535
Epoch: 1 Loss: 0.6461059588397704
Epoch: 1 Loss: 0.05802599144010506
Epoch: 1 Loss: 0.3283810625497236
Epoch: 1 Loss: 0.049597662244349784
Epoch: 1 Loss: 0.009816861644286289
Epoch: 1 Loss: 0.010331376159876164
Epoch: 1 Loss: 0.0868329348540823
Epoch: 1 Loss: 0.14561951113381202
Epoch: 1 Loss: 0.0009445670807321793
Epoch: 1 Loss: 0.04830426607194528
Epoch: 1 Loss: 0.028857751897887255
Epoch: 1 Loss: 0.0955578038263712
Epoch: 1 Loss: 0.052598105909909126
Epoch: 2 Loss: 0.017652218576096987
Epoch: 2 Loss: 0.01443805880290218
Epoch: 2 Loss: 0.12312426510315398
Epoch: 2 Loss: 0.08793901948730633
Epoch: 2 Loss: 0.02126017234437909
Epoch: 2 Loss: 0.01923217256943037
Epoch: 2 Loss: 0.007577542098598239
Epoch: 2 Loss: 0.08560142791569594
Epoch: 2 Loss: 0.0003219596537744652
Epoch: 2 Loss: 0.0697127211047705
Epoch: 2 Loss: 0.004532973016102098
Epoch: 2 Loss: 0.07737262894494543
Epoch: 2 Loss: 0.03316168475009143
Epoch: 2 Loss: 0.030385102318207586
Epoch: 2 Loss: 0.1354652622789627
Epoch: 2 Loss: 0.1569683816384591
Epoch: 2 Loss: 0.12556785073113685
Epoch: 2 Loss: 0.3108604746637796
Epoch: 2 Loss: 0.002590560171025124
Epoch: 2 Loss: 0.0019906344702921687
Epoch: 2 Loss: 0.07839091764767432
Epoch: 2 Loss: 0.001235948542593618
Epoch: 2 Loss: 0.18464126897109337
Epoch: 2 Loss: 0.025260410716344904
Epoch: 2 Loss: 0.003502615764079936
Epoch: 2 Loss: 0.003242577452368808
Epoch: 2 Loss: 0.06680929154157254
Epoch: 2 Loss: 0.08481095236388747
Epoch: 2 Loss: 0.00251185868353771
Epoch: 2 Loss: 0.000587885022557512
Epoch: 2 Loss: 0.2639273642124238
Epoch: 2 Loss: 0.0018713660767438207
Epoch: 2 Loss: 0.1662299998769782
Epoch: 2 Loss: 0.003043053921111102
Epoch: 2 Loss: 0.0013513234642874745
Epoch: 2 Loss: 0.009916555562063457
Epoch: 2 Loss: 0.041653120973425634
Epoch: 2 Loss: 0.2802217600630804
Epoch: 2 Loss: 0.025252587255422572
Epoch: 2 Loss: 0.0023344915698518573
Epoch: 2 Loss: 0.017790844682381717
Epoch: 2 Loss: 0.0018167186858652346
Epoch: 2 Loss: 0.0019648528294563205
Epoch: 2 Loss: 0.07450827058263922
Epoch: 2 Loss: 1.719745694012854e-05
Epoch: 2 Loss: 0.0021311781078219637
Epoch: 2 Loss: 0.019447520471821043
Epoch: 2 Loss: 0.006678317714370683
Epoch: 2 Loss: 0.25823137534565205
Epoch: 2 Loss: 0.0029094056511603066
Epoch: 2 Loss: 0.007340108805036882
Epoch: 2 Loss: 0.003071506269194459
Epoch: 2 Loss: 0.021277267834439957
Epoch: 2 Loss: 0.027163563348094465
Epoch: 2 Loss: 0.2958820666612978
Epoch: 2 Loss: 4.386597283541033e-05
Epoch: 2 Loss: 0.016637421387547056
Epoch: 2 Loss: 0.04701395194978164
Epoch: 2 Loss: 0.23738547015617262
Epoch: 2 Loss: 0.020108953731045827
Epoch: 2 Loss: 0.010076184770525966
Epoch: 2 Loss: 0.028918874021898622
Epoch: 2 Loss: 0.7062955417985346
Epoch: 2 Loss: 0.025079562843003955
Epoch: 2 Loss: 0.16660533661132
Epoch: 2 Loss: 0.001130633689483578
Epoch: 2 Loss: 0.0022886837040876763
Epoch: 2 Loss: 0.31751017620987076
Epoch: 2 Loss: 0.006915760938006612
Epoch: 2 Loss: 0.16276245992700825
Epoch: 2 Loss: 0.061344117280238857
Epoch: 2 Loss: 0.0003102962947772329
Epoch: 2 Loss: 0.05734531931837974
Epoch: 2 Loss: 0.04490637500206135
Epoch: 2 Loss: 0.015689038382921322
Epoch: 2 Loss: 0.03793553045357763
Epoch: 2 Loss: 0.023407925831155595
Epoch: 2 Loss: 0.1520650452934925
Epoch: 2 Loss: 0.0005693249778739642
Epoch: 2 Loss: 0.004042973181049072
Epoch: 2 Loss: 0.0021561642724738017
Epoch: 2 Loss: 0.2410312038361095
Epoch: 2 Loss: 0.003199766947220498
Epoch: 2 Loss: 4.924679690647771e-05
Epoch: 2 Loss: 0.1321969370742182
Epoch: 2 Loss: 0.009991905305241315
Epoch: 2 Loss: 9.28733189338341e-06
Epoch: 2 Loss: 0.30686473019553906
Epoch: 2 Loss: 0.06060727893342316
Epoch: 2 Loss: 0.2041452258239371
Epoch: 2 Loss: 0.0010609542896285757
Epoch: 2 Loss: 0.28203834853180754
Epoch: 2 Loss: 0.0022796778122462272
Epoch: 2 Loss: 0.0089365191234901
Epoch: 2 Loss: 0.001497872666289294
Epoch: 2 Loss: 0.19455919027687874
Epoch: 2 Loss: 0.14222838760199805
Epoch: 2 Loss: 0.0024765702573959665
Epoch: 2 Loss: 0.20064623744110383
Epoch: 2 Loss: 0.9351274247098911
Epoch: 2 Loss: 2.4331408819398144e-06
Epoch: 2 Loss: 0.05584545271156749
Epoch: 2 Loss: 0.9822825743192954
Epoch: 2 Loss: 0.002344171190617715
Epoch: 2 Loss: 0.0027785674933320844
Epoch: 2 Loss: 0.0012204417191574045
Epoch: 2 Loss: 0.019401877318958573
Epoch: 2 Loss: 0.0002441902207054676
Epoch: 2 Loss: 0.008248613224941647
Epoch: 2 Loss: 0.003492764408826369
Epoch: 2 Loss: 0.09403808700989107
Epoch: 2 Loss: 0.0035144738576202285
Epoch: 2 Loss: 0.0001406322338692557
Epoch: 2 Loss: 2.2411853812936245e-05
Epoch: 2 Loss: 0.17723650919152942
Epoch: 2 Loss: 0.019241761050374093
Epoch: 2 Loss: 8.463767609287959e-07
Epoch: 2 Loss: 0.00771735362888728
Epoch: 2 Loss: 0.0387518383420368
Epoch: 2 Loss: 0.004554136539274116
Epoch: 2 Loss: 0.059722433112559675
Epoch: 2 Loss: 0.006820432321757956
Epoch: 2 Loss: 0.020677035650185343
Epoch: 2 Loss: 0.04812127498753731
Epoch: 2 Loss: 0.0036902356257195717
Epoch: 2 Loss: 0.03850310876849464
Epoch: 2 Loss: 0.14446727987147512
Epoch: 2 Loss: 0.054423138949205585
Epoch: 2 Loss: 0.03530483204038213
Epoch: 2 Loss: 0.00014069746028229368
Epoch: 2 Loss: 0.1558800911576473
Epoch: 2 Loss: 0.033544532101526595
Epoch: 2 Loss: 0.000566234037691462
Epoch: 2 Loss: 6.299854409996105e-05
Epoch: 2 Loss: 0.004670296065765363
Epoch: 2 Loss: 0.35305661383068865
Epoch: 2 Loss: 0.45864620613632423
Epoch: 2 Loss: 0.012613780934049579
Epoch: 2 Loss: 0.026642266697534507
Epoch: 2 Loss: 0.0032985812816129605
Epoch: 2 Loss: 0.003905591259776963
Epoch: 2 Loss: 0.0024581429335906292
Epoch: 2 Loss: 0.0037368989585810685
Epoch: 2 Loss: 0.00720901426717425
Epoch: 2 Loss: 0.016253875752650505
Epoch: 2 Loss: 0.008381508678345109
Epoch: 2 Loss: 0.0001809563984592861
Epoch: 2 Loss: 0.0005022502381726978
Epoch: 2 Loss: 0.061586223348370044
Epoch: 2 Loss: 0.0011582534033327814
Epoch: 2 Loss: 0.006373013313731408
Epoch: 2 Loss: 0.01396340852494363
Epoch: 2 Loss: 1.37893235474076e-05
Epoch: 2 Loss: 0.0071370435326303895
Epoch: 2 Loss: 0.008222536865357233
Epoch: 2 Loss: 0.003895098873609331
Epoch: 2 Loss: 0.11886672154565701
Epoch: 2 Loss: 2.8302864487320055e-05
Epoch: 2 Loss: 0.00011614952583334834
Epoch: 2 Loss: 0.0022265942685652513
Epoch: 2 Loss: 0.0036269647859495514
Epoch: 2 Loss: 0.013367580867226978
Epoch: 2 Loss: 0.004888608013015966
Epoch: 2 Loss: 0.15243342105750438
Epoch: 2 Loss: 0.15727858614735862
Epoch: 2 Loss: 0.03113364957666117
Epoch: 2 Loss: 0.0033978864023183103
Epoch: 2 Loss: 0.19237409908244338
Epoch: 2 Loss: 0.008542038031623234
Epoch: 2 Loss: 0.0005100257476742414
Epoch: 2 Loss: 0.03441095212650568
Epoch: 2 Loss: 0.0011144883905152476
Epoch: 2 Loss: 0.010168995134775014
Epoch: 2 Loss: 0.0340482725160214
Epoch: 2 Loss: 0.12220950085374938
Epoch: 2 Loss: 0.0014723697367405703
Epoch: 2 Loss: 0.13227956702749405
Epoch: 2 Loss: 0.05286232959002956
Epoch: 2 Loss: 0.003204140056916811
Epoch: 2 Loss: 5.3853443679489796e-05
Epoch: 2 Loss: 0.099250125426021
Epoch: 2 Loss: 0.0013534790426179954
Epoch: 2 Loss: 0.15986577758534523
Epoch: 2 Loss: 0.010419859480581422
Epoch: 2 Loss: 0.014911452130511621
Epoch: 2 Loss: 0.0013944821199463782
Epoch: 2 Loss: 0.0018382470451631392
Epoch: 2 Loss: 0.010089436951733557
Epoch: 2 Loss: 0.09622339028223559
Epoch: 2 Loss: 0.03644482981229621
Epoch: 2 Loss: 0.000558630997114166
Epoch: 2 Loss: 0.016695367997001578
Epoch: 2 Loss: 2.184745296458644e-05
Epoch: 2 Loss: 0.9268216442181165
Epoch: 2 Loss: 0.006628978034071933
Epoch: 2 Loss: 0.1481616446473039
Epoch: 2 Loss: 0.010118941796135667
Epoch: 2 Loss: 0.006819432902954502
Epoch: 2 Loss: 0.004039064358938427
Epoch: 2 Loss: 0.01083038892232717
Epoch: 2 Loss: 0.0013938250822831172
Epoch: 2 Loss: 0.0006054858507869829
Epoch: 2 Loss: 0.04021872134206532
Epoch: 2 Loss: 0.11124557742829012
Epoch: 2 Loss: 0.020322600810475405
Epoch: 2 Loss: 0.0054052614778580576
Epoch: 2 Loss: 0.00025469761729392254
Epoch: 2 Loss: 0.011949961457062869
Epoch: 2 Loss: 0.01044806135170597
Epoch: 2 Loss: 3.608039717532886e-05
Epoch: 2 Loss: 0.23556844987792222
Epoch: 2 Loss: 0.007967673095032666
Epoch: 2 Loss: 9.528152215830441e-05
Epoch: 2 Loss: 1.1088271155256018
Epoch: 2 Loss: 0.11759388761658274
Epoch: 2 Loss: 0.0903195838772719
Epoch: 2 Loss: 0.006363486060327538
Epoch: 2 Loss: 0.041144594677906536
Epoch: 2 Loss: 0.014756271021431384
Epoch: 2 Loss: 0.1043148135263368
Epoch: 2 Loss: 0.00017824029572151653
Epoch: 2 Loss: 0.024873390370098093
Epoch: 2 Loss: 0.07321886708075058
Epoch: 2 Loss: 2.6173992624286164
Epoch: 2 Loss: 7.578756707918718e-05
Epoch: 2 Loss: 0.4207748587720076
Epoch: 2 Loss: 0.012939844471497647
Epoch: 2 Loss: 0.0033617814222129698
Epoch: 3 Loss: 2.479430516703108e-05
Epoch: 3 Loss: 0.00023119217860230503
Epoch: 3 Loss: 0.027931971508080602
Epoch: 3 Loss: 0.17372885736586688
Epoch: 3 Loss: 0.02632679193005811
Epoch: 3 Loss: 0.06861918825758741
Epoch: 3 Loss: 0.0130172546913142
Epoch: 3 Loss: 0.003371953197568627
Epoch: 3 Loss: 0.0425322354249537
Epoch: 3 Loss: 0.0015838278435909958
Epoch: 3 Loss: 0.0005717390299412194
Epoch: 3 Loss: 0.0017635830339059059
Epoch: 3 Loss: 0.4368410135813553
Epoch: 3 Loss: 0.0003186778906930442
Epoch: 3 Loss: 0.001848815564433772
Epoch: 3 Loss: 0.00030079722341728326
Epoch: 3 Loss: 0.013401746644118629
Epoch: 3 Loss: 0.00014548725115055684
Epoch: 3 Loss: 0.03206239608506968
Epoch: 3 Loss: 0.0004766876555326827
Epoch: 3 Loss: 0.04963072236005287
Epoch: 3 Loss: 0.36970732384578187
Epoch: 3 Loss: 0.005285901923447403
Epoch: 3 Loss: 2.282732260472916
Epoch: 3 Loss: 0.0061205546029910645
Epoch: 3 Loss: 0.005252733221163509
Epoch: 3 Loss: 0.03571995235373497
Epoch: 3 Loss: 0.05352767812452112
Epoch: 3 Loss: 0.00047507941119951855
Epoch: 3 Loss: 0.07757374574580134
Epoch: 3 Loss: 0.10003901056101167
Epoch: 3 Loss: 0.08543952595799449
Epoch: 3 Loss: 5.23530693773332e-05
Epoch: 3 Loss: 0.005982935667691628
Epoch: 3 Loss: 0.010314715694238395
Epoch: 3 Loss: 0.14692384749945625
Epoch: 3 Loss: 0.0008559900507073399
Epoch: 3 Loss: 0.0025867427964761706
Epoch: 3 Loss: 0.02478648386010222
Epoch: 3 Loss: 0.002017315486414293
Epoch: 3 Loss: 0.08045239783903267
Epoch: 3 Loss: 0.420051490116908
Epoch: 3 Loss: 0.0009819947499000042
Epoch: 3 Loss: 0.18397506871166686
Epoch: 3 Loss: 0.12082194234146378
Epoch: 3 Loss: 0.0016836808695227842
Epoch: 3 Loss: 0.0015472706077698786
Epoch: 3 Loss: 0.01574650787259769
Epoch: 3 Loss: 0.00021748728637101033
Epoch: 3 Loss: 0.0020106677371852185
Epoch: 3 Loss: 0.051604853673501
Epoch: 3 Loss: 0.027820488982454174
Epoch: 3 Loss: 0.8624046804275578
Epoch: 3 Loss: 0.005603457249570832
Epoch: 3 Loss: 0.04664501724950385
Epoch: 3 Loss: 0.6401125077036586
Epoch: 3 Loss: 0.050165607221648055
Epoch: 3 Loss: 0.0030200837582360796
Epoch: 3 Loss: 0.1784592171445933
Epoch: 3 Loss: 0.21582204969681978
Epoch: 3 Loss: 2.4973653068324294e-06
Epoch: 3 Loss: 0.0016399516446183096
Epoch: 3 Loss: 0.00010856941090956534
Epoch: 3 Loss: 0.0061594397530362515
Epoch: 3 Loss: 0.0049436863423389585
Epoch: 3 Loss: 0.1017630522084076
Epoch: 3 Loss: 0.023092983813808275
Epoch: 3 Loss: 0.06321955849580631
Epoch: 3 Loss: 0.2576014641995793
Epoch: 3 Loss: 0.041835017098837905
Epoch: 3 Loss: 0.02943424903314977
Epoch: 3 Loss: 0.013450321547833322
Epoch: 3 Loss: 1.0108341521782045
Epoch: 3 Loss: 0.0005902907758567074
Epoch: 3 Loss: 0.09817016149958109
Epoch: 3 Loss: 0.2955118080087396
Epoch: 3 Loss: 0.044717763445738544
Epoch: 3 Loss: 0.009902246236044951
Epoch: 3 Loss: 0.017314768489565657
Epoch: 3 Loss: 0.013936409064515931
Epoch: 3 Loss: 0.13127032205228192
Epoch: 3 Loss: 0.0042122290000410735
Epoch: 3 Loss: 0.02012878531343559
Epoch: 3 Loss: 0.003908291787837578
Epoch: 3 Loss: 0.0015522609384199105
Epoch: 3 Loss: 0.0013823887427677397
Epoch: 3 Loss: 0.26691103942116823
Epoch: 3 Loss: 0.11125220537161076
Epoch: 3 Loss: 0.15603141985657856
Epoch: 3 Loss: 0.06107166461904005
Epoch: 3 Loss: 0.03229047076889182
Epoch: 3 Loss: 0.0012472139445366746
Epoch: 3 Loss: 0.11691736762590164
Epoch: 3 Loss: 0.020027059301195988
Epoch: 3 Loss: 0.012693588896568892
Epoch: 3 Loss: 0.0008582231224711506
Epoch: 3 Loss: 0.02441369595785664
Epoch: 3 Loss: 0.002358919451066382
Epoch: 3 Loss: 0.04769828311136176
Epoch: 3 Loss: 0.022141605864223646
Epoch: 3 Loss: 0.039683371256685945
Epoch: 3 Loss: 0.04045112370500075
Epoch: 3 Loss: 0.009688677424782346
Epoch: 3 Loss: 0.007129185909945203
Epoch: 3 Loss: 0.0001849277928448374
Epoch: 3 Loss: 0.0006136930589185084

In [ ]:
model.eval()
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        y_pred = model.forward(batch_features)
        y_pred = (y_pred > 0.5).float()
        # accuracy = (y_pred == batch_labels).float().mean()
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

print(f"Overall Accuracy = {sum(accuracy_list) / len(accuracy_list)}")

Accuracy: 0.5
Accuracy: 1.0
Accuracy: 1.0
Accuracy: 1.0
Accuracy: 0.5
Accuracy: 1.0
Accuracy: 1.0
Accuracy: 0.5
Accuracy: 0.5
Accuracy: 1.0
Accuracy: 1.0
Accuracy: 1.0
Accuracy: 1.0
Accuracy: 0.5
Accuracy: 0.5
Accuracy: 1.0
Accuracy: 1.0
Accuracy: 0.5
Accuracy: 1.0
Accuracy: 0.5
Accuracy: 0.5
Accuracy: 0.5
Accuracy: 1.0
Accuracy: 0.5
Accuracy: 0.5
Accuracy: 0.5
Accuracy: 1.0
Accuracy: 0.5
Accuracy: 0.5
Accuracy: 1.0
Accuracy: 1.0
Accuracy: 1.0
Accuracy: 1.0
Accuracy: 0.5
Accuracy: 1.0
Accuracy: 0.5
Accuracy: 1.0
Accuracy: 1.0
Accuracy: 1.0
Accuracy: 0.5
Accuracy: 0.5
Accuracy: 0.5
Accuracy: 0.5
Accuracy: 1.0
Accuracy: 0.5
Accuracy: 0.5
Accuracy: 1.0
Accuracy: 1.0
Accuracy: 0.5
Accuracy: 0.5
Accuracy: 0.5
Accuracy: 0.5
Accuracy: 0.5
Accuracy: 1.0
Accuracy: 1.0
Accuracy: 0.5
Accuracy: 1.0